/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coffeemachineproject;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class formCoffee extends javax.swing.JFrame {

    /**
     * Creates new form formCoffee
     */
    ArrayList<CupCoffee> cup = new ArrayList<>();
    CoffeeMachine c1;
private DB db;
    public formCoffee() throws SQLException, ClassNotFoundException {
        db=new DB();
        this.c1 = new CoffeeMachine(new WaterTank(new DB().Water()), new BeansTank(), new Grinder(1),db);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        gRATE = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        bEANS = new javax.swing.JComboBox<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        waterTank = new javax.swing.JTextField();
        Clean = new javax.swing.JTextField();
        Rtank = new javax.swing.JTextField();
        Atank1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Arya = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        lableBox = new javax.swing.JTextField();
        ES = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        gRATE1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        bEANS2 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Add = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jButton9 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Area2 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Grader  Rate :");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        gRATE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Beans Type : ");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        bEANS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arabica", "Robusta" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("content");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("water : ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("Arabica :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setText("Robusta : ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setText("clean : ");

        waterTank.setEditable(false);
        waterTank.setDragEnabled(true);
        waterTank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterTankActionPerformed(evt);
            }
        });

        Clean.setEditable(false);
        Clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CleanActionPerformed(evt);
            }
        });

        Rtank.setEditable(false);
        Rtank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RtankActionPerformed(evt);
            }
        });

        Atank1.setEditable(false);
        Atank1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Atank1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Atank1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Rtank, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Clean, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(waterTank, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(waterTank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Atank1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Rtank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Clean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 200));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("process");

        Arya.setColumns(20);
        Arya.setRows(5);
        jScrollPane1.setViewportView(Arya);

        jButton7.setBackground(new java.awt.Color(255, 0, 51));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton7.setText("start");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        lableBox.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(61, 61, 61)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addComponent(lableBox, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lableBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 249, 320, 190));

        ES.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ES.setText("Espresso");
        ES.setBorder(new javax.swing.border.MatteBorder(null));
        ES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ESActionPerformed(evt);
            }
        });
        jPanel1.add(ES, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 130, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Double Espresso");
        jButton3.setBorder(new javax.swing.border.MatteBorder(null));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 130, -1));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("Americano");
        jButton5.setBorder(new javax.swing.border.MatteBorder(null));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 142, 130, 20));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Double Americano");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 130, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 10, 220));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Grader  Rate :");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 110, -1));

        gRATE1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(gRATE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 110, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Beans Type : ");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 110, -1));

        bEANS2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arabica", "Robusta" }));
        jPanel1.add(bEANS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 110, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffeemachineproject/coffee 2.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 470));

        jTabbedPane1.addTab("make coffee", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(51, 51, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Operations Tab");
        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 520, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Enter the quantity to be added : ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 96, 237, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Add water");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 204, 214, -1));

        Add.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jPanel2.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 146, 223, 30));

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton8.setText("Add Arabica");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 275, 214, -1));

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton6.setText("Add Robusta");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 351, 214, -1));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 71, 50, 274));

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton9.setText("Machine cleaning");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 214, -1));

        Area2.setColumns(20);
        Area2.setRows(5);
        jScrollPane2.setViewportView(Area2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, 120));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffeemachineproject/coffee 2.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 470));

        jTabbedPane1.addTab("oparation tab", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void waterTankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterTankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_waterTankActionPerformed

    private void CleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CleanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CleanActionPerformed

    private void RtankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RtankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RtankActionPerformed

    private void Atank1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Atank1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Atank1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String water = c1.getWater().toString();
        waterTank.setText(water);
        String ar = c1.getBean().toString1();
        Atank1.setText(ar);
        String rb = c1.getBean().toString2();
        Rtank.setText(rb);
        try {
            Clean.setText(new DB().Count() + "");

        } catch (SQLException ex) {
            Logger.getLogger(formCoffee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(formCoffee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void ESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ESActionPerformed
        int Type, grader;
        if (gRATE1.getSelectedIndex() == 0) {
            grader = 1;

        } else if (gRATE1.getSelectedIndex() == 1) {
            grader = 2;

        } else {
            grader = 3;

        }
        if (bEANS2.getSelectedIndex() == 0) { 

            Type = 1;
            CupCoffee cupCoffe = new CupCoffee("Arabica", "Espresso", "single", grader, c1.getWater().getLevleOfWater(), c1.getBean().type1.levle, c1.getBean().type2.levle);
            cup.add(cupCoffe);
            Arya.append(cupCoffe.toString() + "\n");

        } else {

            Type = 2;
            CupCoffee cupCoffe = new CupCoffee("Robusta", "Espresso", "single", grader, c1.getWater().getLevleOfWater(), c1.getBean().type1.levle, c1.getBean().type2.levle);

            cup.add(cupCoffe);
            Arya.append(cupCoffe.toString() + "\n");

        }

        try {
        
            c1.MakeCoffee(Type, 1, 1, grader);
 
        } catch (OutOfWaterException | InterruptedException e) {
            System.out.println("Sorry, the machine is out of water.");
        } catch (OutOfBeansException ex) {
            System.out.println("Sorry, the machine is out of BEANS.");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(formCoffee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(formCoffee.class.getName()).log(Level.SEVERE, null, ex);
        }
           String water = c1.getWater().toString();
        waterTank.setText(water);
        String ar = c1.getBean().toString1();
        Atank1.setText(ar);
        String rb = c1.getBean().toString2();
        Rtank.setText(rb);
        try {
            Clean.setText(new DB().Count() + "");

        } catch (SQLException ex) {
            Logger.getLogger(formCoffee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(formCoffee.class.getName()).log(Level.SEVERE, null, ex);
        }
        lableBox.setText("Done ^_^");
    }//GEN-LAST:event_ESActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try {
            lableBox.setText("The grain is being milled ...");

            int Type, grader;
            if (gRATE1.getSelectedIndex() == 0) {
                grader = 1;
            } else if (gRATE1.getSelectedIndex() == 1) {
                grader = 2;
            } else {
                grader = 3;

            }
            if (bEANS2.getSelectedIndex() == 0) {
                Type = 1;
                CupCoffee cupCoffe = new CupCoffee("Arabica", "Espresso", "double", grader, c1.getWater().getLevleOfWater(), c1.getBean().type1.levle, c1.getBean().type2.levle);

                cup.add(cupCoffe);
                Arya.append(cupCoffe.toString() + "\n");

            } else {
                Type = 2;
                CupCoffee cupCoffe = new CupCoffee("Robusta", "Espresso", "double", grader, c1.getWater().getLevleOfWater(), c1.getBean().type1.levle, c1.getBean().type2.levle);

                cup.add(cupCoffe);
                Arya.append(cupCoffe.toString() + "\n");

            }

            c1.MakeCoffee(Type, 1, 2, grader);
        } catch (InterruptedException ex) {
            Logger.getLogger(formCoffee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (OutOfWaterException ex) {
            Logger.getLogger(formCoffee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (OutOfBeansException ex) {
            Logger.getLogger(formCoffee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(formCoffee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(formCoffee.class.getName()).log(Level.SEVERE, null, ex);
        }
           String water = c1.getWater().toString();
        waterTank.setText(water);
        String ar = c1.getBean().toString1();
        Atank1.setText(ar);
        String rb = c1.getBean().toString2();
        Rtank.setText(rb);
        try {
            Clean.setText(new DB().Count() + "");

        } catch (SQLException ex) {
            Logger.getLogger(formCoffee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(formCoffee.class.getName()).log(Level.SEVERE, null, ex);
        }
        lableBox.setText("Done ^_^");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int Type, grader;
        if (gRATE1.getSelectedIndex() == 0) {
            grader = 1;

        } else if (gRATE1.getSelectedIndex() == 1) {
            grader = 2;

        } else {
            grader = 3;

        }
        if (bEANS2.getSelectedIndex() == 0) { 

            Type = 1;
            CupCoffee cupCoffe = new CupCoffee("Arabica", "Americano", "single", grader, c1.getWater().getLevleOfWater(), c1.getBean().type1.levle, c1.getBean().type2.levle);
            cup.add(cupCoffe);
            Arya.append(cupCoffe.toString() + "\n");

        } else {

            Type = 2;
            CupCoffee cupCoffe = new CupCoffee("Robusta", "Americano", "single", grader, c1.getWater().getLevleOfWater(), c1.getBean().type1.levle, c1.getBean().type2.levle);

            cup.add(cupCoffe);
            Arya.append(cupCoffe.toString() + "\n");

        }

        try {
        
            c1.MakeCoffee(Type, 2, 1, grader);
 
        } catch (OutOfWaterException | InterruptedException e) {
            System.out.println("Sorry, the machine is out of water.");
        } catch (OutOfBeansException ex) {
            System.out.println("Sorry, the machine is out of BEANS.");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(formCoffee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(formCoffee.class.getName()).log(Level.SEVERE, null, ex);
        }
           String water = c1.getWater().toString();
        waterTank.setText(water);
        String ar = c1.getBean().toString1();
        Atank1.setText(ar);
        String rb = c1.getBean().toString2();
        Rtank.setText(rb);
        try {
            Clean.setText(new DB().Count() + "");

        } catch (SQLException ex) {
            Logger.getLogger(formCoffee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(formCoffee.class.getName()).log(Level.SEVERE, null, ex);
        }
        lableBox.setText("Done ^_^");
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        lableBox.setText("The grain is being milled ...");

        try {

            int Type, grader;
            if (gRATE1.getSelectedIndex() == 0) {

                grader = 1;
            } else if (gRATE1.getSelectedIndex() == 1) {
                grader = 2;
            } else {
                grader = 3;

            }
            if (bEANS2.getSelectedIndex() == 0) {
                Type = 1;
                CupCoffee cupCoffe = new CupCoffee("Arabica", "Americano", "single", grader, c1.getWater().getLevleOfWater(), c1.getBean().type1.levle, c1.getBean().type2.levle);

                cup.add(cupCoffe);
                Arya.append(cupCoffe.toString() + "\n");

            } else {
                Type = 2;
                CupCoffee cupCoffe = new CupCoffee("Robusta", "Americano", "single", grader, c1.getWater().getLevleOfWater(), c1.getBean().type1.levle, c1.getBean().type2.levle);

                cup.add(cupCoffe);
                Arya.append(cupCoffe.toString() + "\n");

            }

            c1.MakeCoffee(Type, 2, 2, grader);
        } catch (InterruptedException ex) {
            Logger.getLogger(formCoffee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (OutOfWaterException ex) {
            Logger.getLogger(formCoffee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (OutOfBeansException ex) {
            Logger.getLogger(formCoffee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(formCoffee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(formCoffee.class.getName()).log(Level.SEVERE, null, ex);
        }
         String water = c1.getWater().toString();
        waterTank.setText(water);
        String ar = c1.getBean().toString1();
        Atank1.setText(ar);
        String rb = c1.getBean().toString2();
        Rtank.setText(rb);
        try {
            Clean.setText(new DB().Count() + "");

        } catch (SQLException ex) {
            Logger.getLogger(formCoffee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(formCoffee.class.getName()).log(Level.SEVERE, null, ex);
        }
        lableBox.setText("Done ^_^");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int Water = Integer.parseInt(Add.getText());
        if (Water < 0) {
            JOptionPane.showMessageDialog(null, "woring enter");
        } else if (Water + c1.getWater().getLevleOfWater() > c1.getWater().getCapacity()) {
            JOptionPane.showMessageDialog(null, "There is not enough space");

        } else {
            c1.getWater().fillTank(Water);
            Area2.append("add water " + Water + " \n");
        }

        String water = c1.getWater().toString();
        waterTank.setText(water);
        String ar = c1.getBean().toString1();
        Atank1.setText(ar);
        String rb = c1.getBean().toString2();
        Rtank.setText(rb);
        Clean.setText(c1.count_cup + "");
        Add.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int AR = Integer.parseInt(Add.getText());
        if (AR < 0) {
            JOptionPane.showMessageDialog(null, "woring enter");
        } else if (AR + c1.getBean().getlevleBeans("AR") > 500) {
            JOptionPane.showMessageDialog(null, "There is not enough space");

        } else {
            c1.getBean().addBeans(1, AR);
            Area2.append("add Arabica " + AR + " \n");

        }

        String water = c1.getWater().toString();
        waterTank.setText(water);
        String ar = c1.getBean().toString1();
        Atank1.setText(ar);
        String rb = c1.getBean().toString2();
        Rtank.setText(rb);
        Clean.setText(c1.count_cup + "");
        Add.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int RB = Integer.parseInt(Add.getText());
        if (RB < 0) {
            JOptionPane.showMessageDialog(null, "woring enter");
        } else if (RB + c1.getBean().getlevleBeans("RB") > 500) {
            JOptionPane.showMessageDialog(null, "There is not enough space");

        } else {
            c1.getBean().addBeans(2, RB);
            Area2.append("add Robusta " + RB + " \n");

        }

        String water = c1.getWater().toString();
        waterTank.setText(water);
        String ar = c1.getBean().toString1();
        Atank1.setText(ar);
        String rb = c1.getBean().toString2();
        Rtank.setText(rb);
        Clean.setText(c1.count_cup + "");
        Add.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        c1.count_cup = 0;
        String water = c1.getWater().toString();
        waterTank.setText(water);
        String ar = c1.getBean().toString1();
        Atank1.setText(ar);
        String rb = c1.getBean().toString2();
        Rtank.setText(rb);
        Clean.setText(c1.count_cup + "");
        Add.setText("");
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formCoffee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formCoffee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formCoffee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formCoffee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new formCoffee().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(formCoffee.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(formCoffee.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Add;
    private javax.swing.JTextArea Area2;
    private javax.swing.JTextArea Arya;
    private javax.swing.JTextField Atank1;
    private javax.swing.JTextField Clean;
    private javax.swing.JButton ES;
    private javax.swing.JTextField Rtank;
    private javax.swing.JComboBox<String> bEANS;
    private javax.swing.JComboBox<String> bEANS2;
    private javax.swing.JComboBox<String> gRATE;
    private javax.swing.JComboBox<String> gRATE1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lableBox;
    private javax.swing.JTextField waterTank;
    // End of variables declaration//GEN-END:variables
}
